// <auto-generated />
using System;
using Accounts.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Accounts.Migrations
{
    [DbContext(typeof(UHCContext))]
    partial class UHCContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Accounts.Models.Agents", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("DateRegistered");

                    b.Property<string>("FirstName");

                    b.Property<string>("IdNumber");

                    b.Property<DateTime?>("LastModified");

                    b.Property<string>("LastName");

                    b.Property<string>("MiddleName");

                    b.Property<string>("Password");

                    b.Property<string>("PhoneNumber");

                    b.Property<string>("SUBCOUNTY");

                    b.Property<string>("TerminalId");

                    b.Property<string>("UserName");

                    b.Property<string>("VILLAGE");

                    b.Property<string>("WARD");

                    b.HasKey("Id");

                    b.HasIndex("IdNumber", "TerminalId")
                        .IsUnique()
                        .HasFilter("[IdNumber] IS NOT NULL AND [TerminalId] IS NOT NULL");

                    b.ToTable("Agents");
                });
#pragma warning restore 612, 618
        }
    }
}
